### ISSUE TITLE
Camera Activity - Take Picture

### ISSUE THREAD

**Issue by asgervasio** [asgervasio/picto#6]
Take picture and save to device. Display on screen

**Comment by agrove9** [comment]
1. User logs in
2. System goes to camera 
3. User takes picture
4. Systems saves picture to DB
5. User views picture 
6. User saves picture 
7. System saves picture to device

Extension:
1a. User is auto logged in
     .1: System goes to camera

**Comment by asgervasio** [comment]
Implemented
